
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BPGBARRAS = 6;
  public static final int BPEQUAL = 22;
  public static final int BPCORIZQ = 18;
  public static final int BPCORDER = 19;
  public static final int BPDEG = 2;
  public static final int BPDOUBLE = 5;
  public static final int BPCOMA = 17;
  public static final int BPGRE = 3;
  public static final int BPCADENA = 24;
  public static final int BPDOSPUNTOS = 16;
  public static final int BPARCHIVO = 14;
  public static final int BPGLINEAS = 13;
  public static final int EOF = 0;
  public static final int BPEJEX = 8;
  public static final int BPSTG = 4;
  public static final int BPVALORES = 9;
  public static final int DD = 25;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 23;
  public static final int BPTITULO = 7;
  public static final int BPTTY = 11;
  public static final int BPPTCOMA = 15;
  public static final int BPTTX = 10;
  public static final int BPLLAIZQ = 20;
  public static final int BPLLADER = 21;
  public static final int BPGPIE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BPDEG",
  "BPGRE",
  "BPSTG",
  "BPDOUBLE",
  "BPGBARRAS",
  "BPTITULO",
  "BPEJEX",
  "BPVALORES",
  "BPTTX",
  "BPTTY",
  "BPGPIE",
  "BPGLINEAS",
  "BPARCHIVO",
  "BPPTCOMA",
  "BPDOSPUNTOS",
  "BPCOMA",
  "BPCORIZQ",
  "BPCORDER",
  "BPLLAIZQ",
  "BPLLADER",
  "BPEQUAL",
  "IDENTIFICADOR",
  "BPCADENA",
  "DD"
  };
}

